# Generated by Django 5.1.7 on 2025-03-23 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    dependencies = [
   ('main', '__first__'),
    ]
    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='main.customer')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='main.admin')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'staff'), name='one_on_one_chat_with_admin')],
            },
        ),
    ]
