# Generated by Django 5.2 on 2025-05-13 17:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('over', 'Over'), ('cancelled', 'cancelled')], default='pending', max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('rooms', models.PositiveBigIntegerField(default=1)),
                ('total_nights', models.PositiveIntegerField(editable=False)),
                ('guests', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('over', 'Over'), ('cancelled', 'cancelled')], default='pending', max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tickets', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField()),
                ('departure_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.departuretrip')),
                ('hotel_reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_reservation', to='reservation.hotelreservation')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='hotelreservation',
            index=models.Index(fields=['status'], name='reservation_status_843d29_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelreservation',
            index=models.Index(fields=['check_out'], name='reservation_check_o_ab58a3_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelreservation',
            index=models.Index(fields=['created_at'], name='reservation_created_fec15f_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelreservation',
            index=models.Index(fields=['hotel'], name='reservation_hotel_i_b37d83_idx'),
        ),
        migrations.AddIndex(
            model_name='tripreservation',
            index=models.Index(fields=['status'], name='reservation_status_da770f_idx'),
        ),
        migrations.AddIndex(
            model_name='tripreservation',
            index=models.Index(fields=['date'], name='reservation_date_649ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='tripreservation',
            index=models.Index(fields=['created_at'], name='reservation_created_694024_idx'),
        ),
        migrations.AddIndex(
            model_name='tripreservation',
            index=models.Index(fields=['trip'], name='reservation_trip_id_c060f7_idx'),
        ),
    ]
