# Generated by Django 5.1.7 on 2025-04-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripreservation',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
