# Generated by Django 5.1.7 on 2025-04-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelreservation',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='hotelreservation',
            name='room_details',
        ),
        migrations.RemoveField(
            model_name='tripreservation',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='rooms',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='tripreservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=10),
        ),
    ]
