# Generated by Django 5.1.7 on 2025-04-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_hotelreservation_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('over', 'Over')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripreservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('over', 'Over')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='tripreservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
