# Generated by Django 5.1.7 on 2025-04-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_trip_main_trip_status_fd5b22_idx'),
        ('reservation', '0002_alter_tripreservation_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hotelreservation',
            index=models.Index(fields=['status'], name='reservation_status_843d29_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelreservation',
            index=models.Index(fields=['check_out'], name='reservation_check_o_ab58a3_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelreservation',
            index=models.Index(fields=['created_at'], name='reservation_created_fec15f_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelreservation',
            index=models.Index(fields=['hotel'], name='reservation_hotel_i_b37d83_idx'),
        ),
        migrations.AddIndex(
            model_name='tripreservation',
            index=models.Index(fields=['status'], name='reservation_status_da770f_idx'),
        ),
        migrations.AddIndex(
            model_name='tripreservation',
            index=models.Index(fields=['date'], name='reservation_date_649ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='tripreservation',
            index=models.Index(fields=['created_at'], name='reservation_created_694024_idx'),
        ),
        migrations.AddIndex(
            model_name='tripreservation',
            index=models.Index(fields=['trip'], name='reservation_trip_id_c060f7_idx'),
        ),
    ]
