# Generated by Django 5.2 on 2025-04-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
