# Generated by Django 5.1.7 on 2025-03-25 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='available_rooms',
        ),
    ]
