# Generated by Django 5.2 on 2025-04-12 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotel', 'verbose_name_plural': 'Hotels'},
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='star_rating',
            new_name='stars_rating',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rooms',
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(default='Unknown address', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=60.99, max_digits=6),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hotel'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='department',
            field=models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff'), ('tour_guide', 'Tour Guide'), ('customer_support', 'Customer Support'), ('hotel_manager', 'Hotel Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='total_occupied_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
