# Generated by Django 5.1.7 on 2025-03-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='star_rating',
            new_name='stars_rating',
        ),
    ]
