# Generated by Django 5.2 on 2025-04-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationdm',
            name='conversation_type',
            field=models.CharField(choices=[('direct', 'Direct Message'), ('support', 'Support Ticket')], default='direct', max_length=10),
        ),
    ]
