# Generated by Django 5.1.7 on 2025-04-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagedm',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='deletionrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupchatconversation',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='groupchatconversation',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='messagegroup',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='messagedm',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='messagedm',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='messagegroup',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConversationDM',
        ),
        migrations.DeleteModel(
            name='DeletionRequest',
        ),
        migrations.DeleteModel(
            name='GroupChatConversation',
        ),
        migrations.DeleteModel(
            name='MessageDM',
        ),
        migrations.DeleteModel(
            name='MessageGroup',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
