# Generated by Django 5.1.7 on 2025-03-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_hotel_available_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.JSONField(blank=True, null=True, verbose_name=list),
        ),
    ]
