# Generated by Django 5.1.7 on 2025-03-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_star_rating_hotel_stars_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='department',
            field=models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff'), ('tour_guide', 'Tour Guide'), ('customer_support', 'Customer Support'), ('hotel_manager', 'Hotel Manager')], max_length=20),
        ),
    ]
