# Generated by Django 5.1.7 on 2025-03-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_hotel_amenities_delete_amenity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
    ]
