# Generated by Django 5.1.7 on 2025-03-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_admin_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='transport',
            field=models.CharField(choices=[('car', 'car'), ('bus', 'bus'), ('air-plane', 'air-plane'), ('cruise', 'Cruise Ship')], max_length=50),
        ),
    ]
