# Generated by Django 5.2 on 2025-04-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/profile.png', upload_to='profile_pictures/admins'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/profile.png', upload_to='profile_pictures/customers'),
        ),
    ]
