# Generated by Django 5.1.7 on 2025-04-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_trip_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='rooms',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
