# Generated by Django 5.1.7 on 2025-03-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_hotel_amenities'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hotel',
            name='unique_hotel_signature',
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_hotel_signature'),
        ),
    ]
