# Generated by Django 5.1.7 on 2025-03-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_hotel_unique_hotel_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.JSONField(blank=True, null=True, verbose_name=list),
        ),
    ]
