# Generated by Django 5.2 on 2025-04-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_admin_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/profile.png', upload_to='profile_pictures/customers/'),
        ),
    ]
