# Generated by Django 5.1.7 on 2025-04-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_hotel_rooms_alter_hotel_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
