# Generated by Django 5.1.7 on 2025-04-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_hotel_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
