# Generated by Django 5.1.7 on 2025-04-11 20:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_hotel_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartureTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sold_tickets', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
        ),
        migrations.RemoveField(
            model_name='chatbotconversation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messagebot',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationdm',
            name='cust',
        ),
        migrations.RemoveField(
            model_name='conversationdm',
            name='last_message',
        ),
        migrations.RemoveField(
            model_name='conversationdm',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='messagedm',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='groupchatconversation',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='groupchatconversation',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='messagegroup',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='messagedm',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='messagedm',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='messagegroup',
            name='sender',
        ),
        migrations.RemoveConstraint(
            model_name='hotel',
            name='unique_hotel_signature',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='city',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='country',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='price',
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=60.99, max_digits=6),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hotel'),
        ),
        migrations.AddField(
            model_name='trip',
            name='stars_rating',
            field=models.FloatField(db_default=3, help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))]),
        ),
        migrations.AlterField(
            model_name='admin',
            name='department',
            field=models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff'), ('tour_guide', 'Tour Guide'), ('customer_support', 'Customer Support'), ('hotel_manager', 'Hotel Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='total_occupied_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='sold_tickets',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='departuretrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_places', to='main.trip'),
        ),
        migrations.DeleteModel(
            name='ChatbotConversation',
        ),
        migrations.DeleteModel(
            name='MessageBot',
        ),
        migrations.DeleteModel(
            name='ConversationDM',
        ),
        migrations.DeleteModel(
            name='GroupChatConversation',
        ),
        migrations.DeleteModel(
            name='MessageDM',
        ),
        migrations.DeleteModel(
            name='MessageGroup',
        ),
    ]
