# Generated by Django 5.1.7 on 2025-03-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_trip_departure_city_alter_admin_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure_city',
            field=models.CharField(max_length=50),
        ),
    ]
