# Generated by Django 5.1.7 on 2025-04-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_departuretrip_remove_chatbotconversation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default='customer/profile.png', null=True, upload_to='profile_pictures/customers'),
        ),
    ]
