# Generated by Django 5.1.7 on 2025-04-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_hotel_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=60.99, max_digits=6),
        ),
    ]
