# Generated by Django 5.1.7 on 2025-03-23 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_admin_user_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatconversation',
            name='participants',
            field=models.ManyToManyField(related_name='chat_group_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupchatconversation',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_group_chat', to='main.trip'),
        ),
        migrations.AlterField(
            model_name='messagedm',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='main.conversationdm'),
        ),
        migrations.AlterField(
            model_name='messagedm',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagedm',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagegroup',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='main.groupchatconversation'),
        ),
        migrations.AlterField(
            model_name='messagegroup',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_group_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
