# Generated by Django 5.1.7 on 2025-04-02 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_hotel_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hotel'),
        ),
    ]
