# Generated by Django 5.1.7 on 2025-04-19 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_groupchatconversation_participants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='conversationdm',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='purchased_trips',
        ),
        migrations.AddField(
            model_name='conversationdm',
            name='conversation_type',
            field=models.CharField(choices=[('support', 'Support Ticket'), ('direct', 'Direct Message')], default='direct', max_length=10),
        ),
        migrations.AddField(
            model_name='messagedm',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='purchasers',
            field=models.ManyToManyField(blank=True, help_text='Customers who have purchased this trip', related_name='purchased_trips', to='main.customer'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='groupmessagereadstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.messagegroup'),
        ),
        migrations.AddField(
            model_name='groupmessagereadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='read_by',
            field=models.ManyToManyField(related_name='read_group_messages', through='main.GroupMessageReadStatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.admin'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
        migrations.AddField(
            model_name='conversationdm',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.supportticket'),
        ),
        migrations.AddConstraint(
            model_name='conversationdm',
            constraint=models.UniqueConstraint(fields=('staff', 'cust', 'ticket'), name='unique_conversation'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmessagereadstatus',
            unique_together={('message', 'user')},
        ),
    ]
