# Generated by Django 5.1.7 on 2025-03-20 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_trip_departure_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='star_rating',
            field=models.PositiveSmallIntegerField(db_default=3, help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
