# Generated by Django 5.1.7 on 2025-04-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_groupmessagereadstatus_supportticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profile_picture',
            field=models.ImageField(default='admins/profile.png', null=True, upload_to='profile_pictures/admins'),
        ),
        migrations.AlterField(
            model_name='conversationdm',
            name='conversation_type',
            field=models.CharField(choices=[('direct', 'Direct Message'), ('support', 'Support Ticket')], default='direct', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default='customer/profile.png', null=True, upload_to='profile_pictures/customers'),
        ),
    ]
