# Generated by Django 5.1.7 on 2025-03-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_trip_star_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='star_rating',
            new_name='stars_rating',
        ),
    ]
