# Generated by Django 5.1.7 on 2025-04-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_trip_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagebot',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='ChatbotConversation',
        ),
        migrations.DeleteModel(
            name='MessageBot',
        ),
    ]
