# Generated by Django 5.1.7 on 2025-04-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_messagebot_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Reservation', 'Reservation'), ('Payment', 'Payment'), ('Trip', 'Trip'), ('Security', 'Security')], max_length=50),
        ),
    ]
