# Generated by Django 5.1.7 on 2025-03-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_star_rating_trip_stars_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='sold_tickets',
            field=models.IntegerField(db_default=0, default=0),
        ),
    ]
