# Generated by Django 5.1.7 on 2025-04-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
