# Generated by Django 5.1.7 on 2025-03-20 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_trip_sold_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='stars_rating',
            field=models.FloatField(db_default=3, help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
