# Generated by Django 5.1.7 on 2025-04-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_notification_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Reservation', 'Reservation'), ('Payment', 'Payment'), ('Trip', 'Trip'), ('Security', 'Security'), ('Hotel', 'Hotel')], max_length=50),
        ),
    ]
