# Generated by Django 5.1.7 on 2025-04-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_notification_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(default='coming', max_length=10),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['is_one_way', 'departure_date'], name='main_trip_is_one__426bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['is_one_way', 'return_date'], name='main_trip_is_one__324eb4_idx'),
        ),
    ]
