# Generated by Django 5.1.7 on 2025-04-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_trip_status_trip_main_trip_is_one__426bd5_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='main_trip_status_fd5b22_idx'),
        ),
    ]
