# Generated by Django 5.1.7 on 2025-04-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_trip_main_trip_status_fd5b22_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default='profile.png', upload_to='profile_pictures/customers/'),
        ),
    ]
