# Generated by Django 5.1.7 on 2025-04-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_customer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default='profile.png', upload_to='profile_pictures/customers'),
        ),
    ]
