# Generated by Django 5.1.7 on 2025-04-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_customer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profile_picture',
            field=models.ImageField(default='profile.png', upload_to='profile_pictures/admins'),
        ),
    ]
