# Generated by Django 5.1.7 on 2025-04-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_admin_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/profile.png', upload_to='profile_pictures/admins'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/profile.png', upload_to='profile_pictures/customers'),
        ),
    ]
