// app/layout.js
import { Urbanist } from "next/font/google";
import { AuthProvider } from "./context/AuthContext";
import { SearchProvider } from "./context/SearchContext";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./components/Loading";
import { FormProvider } from "./context/FormContext";
import Footer from "./components/Footer";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Escapeo",
  description: "Generated by create next app",
};

import { TripContext } from "./Setting/context/tripContext";


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={urbanist.variable}>
      <body style={{ fontFamily: "urbanist", color: "black" }}>
        <AuthProvider>
          <SearchProvider>
            <FormProvider>
               <Suspense fallback={<Loading />}>
                  {children}

                </Suspense>
             </FormProvider>
          </SearchProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
