import { Urbanist } from "next/font/google"; // Import Urbanist
import NavbarConnected from "./components/NavbarConnected";

import "./globals.css";

// Configure Urbanist
const urbanist = Urbanist({
  variable: "--font-urbanist", // Define a CSS variable for Urbanist
  subsets: ["latin"],
  weight: "400", // Specify the font weight
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={urbanist.variable}>
      <body style={{
        fontFamily:'urbanist'
      }}>
        <NavbarConnected />
        {children}
      </body>
    </html>
  );
}