


import { Urbanist } from "next/font/google"; // Import Urbanist
import NavbarConnected from "./components/NavBar";
import { AuthProvider, useAuth } from './context/AuthContext'; // Import AuthProvider
import "./globals.css";
import NavBar from "./components/NavBar";

// Configure Urbanist
const urbanist = Urbanist({
  variable: "--font-urbanist", // Define a CSS variable for Urbanist
  subsets: ["latin"],
  weight: "400", // Specify the font weight
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  

  return (
    <html lang="en" className={urbanist.variable}>
      <body style={{ fontFamily: 'urbanist' , color:'black' }}>
        {/* Wrap the entire application with AuthProvider */}
        
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}