# Generated by Django 5.1.7 on 2025-04-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
