import { Urbanist } from "next/font/google";
import { AuthProvider } from './context/AuthContext'; // Import AuthProvider
import  {SearchProvider}  from './context/SearchContext'
import "./globals.css";

// Configure Urbanist
const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={urbanist.variable}>
      <body style={{ fontFamily: 'urbanist', color: 'black' }}>
        {/* Wrap the entire application with AuthProvider */}
        <AuthProvider>
        <SearchProvider>
        {children}
        </SearchProvider>
        </AuthProvider>
      </body>
    </html>
  );
}